### ISSUE TITLE
Missing Extensions

### ISSUE THREAD

**Issue by wbrawner** [flathub/org.mapeditor.Tiled#26]
The Flatpak build seems to be missing quite a few extensions compared to the official build. See the screenshots for comparison:

<details>
<summary>Flatpak build extensions</summary>
<img src="https://github.com/flathub/org.mapeditor.Tiled/assets/11827417/d7e88a09-6604-485c-b1e6-33e0bc0efa8d" />
</details>

<details>
<summary>Official (AppImage) build extensions</summary>
<img src="https://github.com/flathub/org.mapeditor.Tiled/assets/11827417/c8aa4425-f00e-4408-9a26-242e21753324" />
</details>

Is this intentional?

**Comment by bjorn** [comment]
> Is this intentional?

Hmm, no, that's definitely not intended. It's very unexpected, because all of these plugins are built-in and none of them, except for the Python one, have additional conditions on whether they should be included or not.

The issue also doesn't appear universal, because I have the Flatpak installed as well, and for me it does show all the expected plugins:

![image](https://github.com/flathub/org.mapeditor.Tiled/assets/531764/ff69266e-400a-4c9c-95b6-2cda9bc1b5f0)

Does the output of `flatpak info org.mapeditor.Tiled/x86_64/stable` match mine?

```
bjorn@thor:~$ flatpak info org.mapeditor.Tiled/x86_64/stable

Tiled - General purpose map editor

          ID: org.mapeditor.Tiled
         Ref: app/org.mapeditor.Tiled/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.10.2
     License: GPL-2.0+ and BSD-2-Clause
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 13.5 MB
     Runtime: org.kde.Platform/x86_64/6.4
         Sdk: org.kde.Sdk/x86_64/6.4

      Commit: 693826c1eddf6ba7b8eac6e1371d9efca7b9a3a4e7571a0b6fa34cc7a6b3e6d2
      Parent: 0ec5bde38939d53fd557c6045ee46c836bcc3f7026eec59d1ed8800a9824b04f
     Subject: Update to Tiled 1.10.2 (46ad2747)
        Date: 2023-08-07 10:14:25 +0000
```

**Comment by wbrawner** [comment]
I apologize for the mistake. I ran that command and after some digging, realized I had installed the RPM from Gnome Software, not the Flatpak :man_facepalming:

This is why I do most things in the terminal :man_facepalming: Sorry for the trouble!

**Comment by bjorn** [comment]
@wbrawner Ah, of course! Note that if you prefer the RPM, you can also use that, but at least Fedora decided to put some of the plugins in separate packages, so you'd have to install the `tiled-plugin-...` packages for the plugins you need.

**Comment by wbrawner** [comment]
Ah, that's good to know for the future. Thanks!
